global:
  logLevel: info
  splunk:
    hec:
      protocol: https
      insecureSSL: true
      host: $SPLUNK_HEC_HOST_PERF
      token: $SPLUNK_HEC_TOKEN_PERF

splunk-kubernetes-logging:
  kubernetes:
    insecureSSL: true
  splunk:
    hec:
      indexName: perf_test_events
  image:
    pullPolicy: Always

splunk-kubernetes-metrics:
  kubernetes:
    useRestClientSSL: false
    insecureSSL: true
    kubeletPort: 10255
  splunk:
    hec:
      indexName: perf_test_metrics
  image:
    pullPolicy: Always

splunk-kubernetes-objects:
  splunk:
    hec:
      indexName: perf_test_objects
  kubernetes:
    insecureSSL: true
  image:
    pullPolicy: Always